import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { BookOpen, BrainCircuit, CheckCircle2, ChevronRight, CircleHelp, Compass, Filter, Flame, GraduationCap, LayoutDashboard, Menu, Search, Sparkles, Target, X } from "lucide-react";
import { toast, Toaster } from "sonner";

const stages = ["Todos os níveis", "Fundamental 1", "Fundamental 2", "Ensino Médio", "ENEM", "Pré-vestibular"];
const subjects = ["Todas", "Matemática", "Português", "Biologia", "História", "Física"];
const API = `${process.env.REACT_APP_BACKEND_URL}/api`;

function Sidebar({ active, setActive, open, setOpen }) {
  const links = [["Visão geral", LayoutDashboard], ["Minha trilha", Compass], ["Biblioteca", BookOpen], ["Questões", CircleHelp]];
  return <aside className={`sidebar ${open ? "is-open" : ""}`} data-testid="main-sidebar">
    <div className="brand"><div className="brand-mark"><Sparkles size={18}/></div><span>EduBoost <b>Pro</b></span><button className="mobile-close" onClick={() => setOpen(false)} data-testid="sidebar-close-button"><X size={18}/></button></div>
    <div className="side-label">APRENDER</div>
    <nav>{links.map(([label, Icon]) => <button key={label} className={active === label ? "nav-link active" : "nav-link"} onClick={() => { setActive(label); setOpen(false); }} data-testid={`nav-${label.toLowerCase().replaceAll(" ", "-")}`}><Icon size={18}/><span>{label}</span>{active === label && <span className="nav-dot"/>}</button>)}</nav>
    <div className="side-promo"><div className="promo-icon"><Flame size={18}/></div><strong>Seu ritmo está<br/>pegando fogo!</strong><span>3 dias seguidos estudando</span><div className="streak-bar"><i/></div></div>
    <div className="profile"><div className="avatar">AM</div><div><strong>Alex Martins</strong><span>8º ano · Explorador</span></div><ChevronRight size={16}/></div>
  </aside>
}

function Library({ setActive }) {
  const [stage, setStage] = useState("Todos os níveis"); const [subject, setSubject] = useState("Todas"); const [items, setItems] = useState([]); const [search, setSearch] = useState("");
  useEffect(() => { axios.get(`${API}/library`).then(({data}) => setItems(data.items)).catch(() => toast.error("Não foi possível carregar a biblioteca")); }, []);
  const filtered = useMemo(() => items.filter(x => (stage === "Todos os níveis" || x.stage === stage) && (subject === "Todas" || x.subject === subject) && x.title.toLowerCase().includes(search.toLowerCase())), [items, stage, subject, search]);
  return <section className="library-page"><div className="page-heading"><div><div className="eyebrow">BIBLIOTECA UNIVERSAL</div><h1>Encontre seu próximo <em>salto.</em></h1><p>Conteúdo autoral, direto ao ponto e no ritmo da sua fase escolar.</p></div><div className="heading-art"><BookOpen size={38}/><span>+ 240 aulas<br/>em construção</span></div></div>
    <div className="search-row"><div className="search-box"><Search size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar uma aula, tema ou matéria" data-testid="library-search-input"/></div><button className="filter-button" data-testid="library-filter-button"><Filter size={17}/> Filtros</button></div>
    <div className="filter-scroll">{stages.map(x => <button className={stage === x ? "chip selected" : "chip"} onClick={() => setStage(x)} key={x} data-testid={`stage-filter-${x.toLowerCase().replaceAll(" ", "-")}`}>{x}</button>)}</div>
    <div className="section-head"><div><span className="eyebrow">CURADORIA PARA VOCÊ</span><h2>Continue explorando</h2></div><div className="subject-tabs">{subjects.map(x => <button className={subject === x ? "subject-tab selected" : "subject-tab"} onClick={() => setSubject(x)} key={x} data-testid={`subject-filter-${x.toLowerCase()}`}>{x}</button>)}</div></div>
    <div className="library-grid">{filtered.map(item => <article className="study-card" key={item.id} data-testid={`library-card-${item.id}`}><div className={`card-art ${item.color}`}><span>{item.subject}</span><BookOpen size={28}/><strong>{item.title}</strong></div><div className="study-body"><div className="study-meta"><span>{item.stage}</span><span>{item.lessons} aulas</span></div><p>{item.description}</p><div className="progress-label"><span>{item.progress ? `${item.progress}% concluído` : "Comece agora"}</span><b>{item.progress}%</b></div><div className="progress-track"><i style={{width: `${item.progress}%`}}/></div><button onClick={() => {setActive("Minha trilha"); toast.success("Aula adicionada à sua trilha")}} data-testid={`library-start-${item.id}`}>{item.progress ? "Continuar aula" : "Adicionar à trilha"}<ChevronRight size={16}/></button></div></article>)}</div>
  </section>
}

function Dashboard({ setActive }) { return <section className="dashboard"><div className="welcome"><div><div className="eyebrow">SEGUNDA-FEIRA, 12 DE MAIO</div><h1>Olá, Alex. <em>Vamos avançar?</em></h1><p>Seu mapa de estudos está pronto para hoje.</p></div><button className="primary-button" onClick={() => setActive("Biblioteca")} data-testid="welcome-library-button"><BookOpen size={17}/> Explorar biblioteca</button></div><div className="dashboard-grid"><div className="focus-panel"><div className="panel-top"><div><span className="eyebrow">FOCO DE HOJE</span><h2>Continue de onde parou</h2></div><span className="duration">15 min</span></div><div className="focus-content"><div className="focus-cover"><BrainCircuit size={34}/><span>MATEMÁTICA</span></div><div><h3>Frações no dia a dia</h3><p>Entenda partes, inteiros e como comparar frações com facilidade.</p><button className="text-button" onClick={() => toast.success("Aula iniciada") } data-testid="start-focus-button">Começar aula <ChevronRight size={16}/></button></div></div></div><div className="progress-panel"><span className="eyebrow">SUA SEMANA</span><h2>Constância vence pressa.</h2><div className="week"><div className="days"><span>SEG</span><i className="done">✓</i><span>TER</span><i className="done">✓</i><span>QUA</span><i className="today">•</i><span>QUI</span><i>·</i><span>SEX</span><i>·</i></div></div><div className="percent"><strong>68%</strong><span>do seu objetivo semanal</span></div></div></div><div className="lower-grid"><div><div className="section-head compact"><div><span className="eyebrow">SUGESTÕES INTELIGENTES</span><h2>Para o seu momento</h2></div><button className="link-button" onClick={() => setActive("Biblioteca")} data-testid="see-all-library-button">Ver biblioteca <ChevronRight size={15}/></button></div><div className="suggestions"><div className="suggestion blue"><Target size={22}/><span>Desafio rápido</span><strong>3 questões de lógica</strong><button onClick={() => setActive("Questões")} data-testid="quick-challenge-button">Resolver agora <ChevronRight size={15}/></button></div><div className="suggestion coral"><Sparkles size={22}/><span>Trilha recomendada</span><strong>Português sem medo</strong><button onClick={() => setActive("Minha trilha")} data-testid="recommended-trail-button">Ver trilha <ChevronRight size={15}/></button></div></div></div><div className="quote"><span>“</span><p>Aprender não é chegar mais rápido. É perceber que você consegue ir mais longe.</p><small>— seu espaço de estudos</small></div></div></section> }

function Diagnostic({ setActive }) { const [grade, setGrade] = useState("Ensino Médio"); const [focus, setFocus] = useState("Matemática"); const [confidence, setConfidence] = useState("Estou começando"); const [loading, setLoading] = useState(false); const [result, setResult] = useState(""); const submit = async () => { setLoading(true); try { const {data} = await axios.post(`${API}/diagnostic`, {grade, focus, confidence}); setResult(data.response); toast.success("Sua trilha foi criada"); } catch { toast.error("A IA está ocupada. Tente novamente em instantes."); } finally { setLoading(false); } }; return <section className="diagnostic-page"><div className="page-heading"><div><div className="eyebrow">DIAGNÓSTICO INTELIGENTE</div><h1>Uma trilha feita para <em>você.</em></h1><p>Conte como você aprende. A gente adapta o caminho.</p></div><div className="diagnostic-orbit"><BrainCircuit size={42}/></div></div><div className="diagnostic-layout"><div className="diagnostic-form"><span className="step-label">01 / 03</span><h2>Em qual fase você está?</h2><p>Isso ajuda a ajustar a linguagem e a profundidade das aulas.</p><div className="option-grid">{["Fundamental 1","Fundamental 2","Ensino Médio","ENEM / Vestibular"].map(x => <button className={grade === x ? "option selected" : "option"} onClick={() => setGrade(x)} key={x} data-testid={`diagnostic-grade-${x.toLowerCase().replaceAll(" ", "-")}`}>{x}<CheckCircle2 size={17}/></button>)}</div><label>Qual matéria merece mais atenção agora?</label><select value={focus} onChange={e => setFocus(e.target.value)} data-testid="diagnostic-subject-select">{subjects.slice(1).map(x => <option key={x}>{x}</option>)}</select><label>Como você se sente com ela?</label><div className="confidence-row">{["Estou começando","Sei o básico","Quero aprofundar"].map(x => <button className={confidence === x ? "confidence selected" : "confidence"} onClick={() => setConfidence(x)} key={x} data-testid={`diagnostic-confidence-${x.toLowerCase().replaceAll(" ", "-")}`}>{x}</button>)}</div><button className="primary-button full" onClick={submit} disabled={loading} data-testid="diagnostic-submit-button">{loading ? "Criando sua trilha..." : "Criar minha trilha"}<Sparkles size={17}/></button></div><div className="diagnostic-result">{result ? <><span className="eyebrow">SUA NOVA TRILHA</span><h2>O caminho começa aqui.</h2><div className="ai-result" data-testid="diagnostic-result">{result}</div><button className="text-button" onClick={() => setActive("Minha trilha")} data-testid="open-trail-button">Abrir trilha completa <ChevronRight size={16}/></button></> : <><div className="result-icon"><Sparkles size={24}/></div><h3>Seu mapa de aprendizagem</h3><p>Responda ao diagnóstico e receba uma sequência de estudos que respeita seu momento, seu ritmo e suas conquistas.</p><div className="result-lines"><span/><span/><span/></div></>}</div></div></section> }

function Questions() { const [subject, setSubject] = useState("Matemática"); const [topic, setTopic] = useState("Frações"); const [level, setLevel] = useState("Intermediário"); const [result, setResult] = useState(""); const [loading, setLoading] = useState(false); const generate = async () => { setLoading(true); try { const {data} = await axios.post(`${API}/questions`, {subject, topic, level}); setResult(data.response); } catch { toast.error("Não foi possível gerar a questão agora"); } finally { setLoading(false); } }; return <section className="questions-page"><div className="page-heading"><div><div className="eyebrow">BANCO DE QUESTÕES</div><h1>Aprenda fazendo <em>conexões.</em></h1><p>Questões autorais para transformar teoria em confiança.</p></div><div className="question-mark"><CircleHelp size={40}/></div></div><div className="question-layout"><div className="question-controls"><span className="eyebrow">PERSONALIZE O DESAFIO</span><label>Matéria</label><select value={subject} onChange={e => setSubject(e.target.value)} data-testid="question-subject-select">{subjects.slice(1).map(x => <option key={x}>{x}</option>)}</select><label>Tema</label><input value={topic} onChange={e => setTopic(e.target.value)} data-testid="question-topic-input"/><label>Nível</label><div className="level-row">{["Iniciante","Intermediário","Avançado"].map(x => <button className={level === x ? "level selected" : "level"} onClick={() => setLevel(x)} key={x} data-testid={`question-level-${x.toLowerCase()}`}>{x}</button>)}</div><button className="primary-button full" onClick={generate} disabled={loading} data-testid="generate-question-button">{loading ? "Criando questão..." : "Gerar questão"}<Sparkles size={17}/></button></div><div className="question-result">{result ? <div className="ai-result" data-testid="question-result">{result}</div> : <><div className="question-empty-icon"><CircleHelp size={27}/></div><h2>Seu próximo desafio espera.</h2><p>Escolha a matéria e o nível. A resolução detalhada aparece depois que você tentar.</p></>}</div></div></section> }

function App() {
  const [active, setActive] = useState("Visão geral"); const [open, setOpen] = useState(false); const content = active === "Biblioteca" ? <Library setActive={setActive}/> : active === "Questões" ? <Questions/> : active === "Minha trilha" ? <Diagnostic setActive={setActive}/> : <Dashboard setActive={setActive}/>;
  return <div className="app-shell"><Sidebar active={active} setActive={setActive} open={open} setOpen={setOpen}/><main className="main-content"><header className="topbar"><button className="menu-button" onClick={() => setOpen(true)} data-testid="sidebar-menu-button"><Menu size={21}/></button><div className="breadcrumb"><span>Meu espaço</span><ChevronRight size={14}/><b>{active}</b></div><div className="top-actions"><div className="top-streak"><Flame size={17}/> 3 dias</div><div className="mini-avatar">AM</div></div></header>{content}</main><Toaster position="top-right"/></div>;
}

export default App;
